name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  main:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      EX_RATATUI_BUILD: "true"

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.19"
            otp: "28"
            lint: true
          - elixir: "1.18"
            otp: "27"
          - elixir: "1.17"
            otp: "26"

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/cache@v4
        if: ${{ ! matrix.lint }}
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            native/ex_ratatui/target
          key: cargo-${{ runner.os }}-${{ hashFiles('native/ex_ratatui/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}-

      - run: mix deps.get --check-locked

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix compile --warnings-as-errors

      - name: Run cargo tests
        run: cargo test --manifest-path native/ex_ratatui/Cargo.toml

      - run: mix test
